#!/usr/bin/env bash
export XSECURELOCK_FONT="JetBrains Mono-24"
export XSECURELOCK_PASSWORD_PROMPT="asterisks"
export XSECURELOCK_AUTH_FOREGROUND_COLOR="#ebdbb2"
export XSECURELOCK_AUTH_BACKGROUND_COLOR="#282828"
export XSECURELOCK_BACKGROUND_COLOR="#282828"
export XSECURELOCK_AUTH_CURSOR_BLINK=1
export XSECURELOCK_NO_COMPOSITE=1
